### ISSUE TITLE
Switch from XML to JSON

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Appclusive.UI#39]

**Comment by rufer7** [comment]
@dfch do you know by heart how to set the format on the service reference?

**Comment by ChrEggenberger** [comment]
Adding a header works like this:

protected biz.dfch.CS.Appclusive.Api.Core.Core CoreRepository
        {
            get
            {
                if (coreRepository == null)
                {
                    coreRepository = new biz.dfch.CS.Appclusive.Api.Core.Core(new Uri(Properties.Settings.Default.AppculsiveApiCoreUrl));
                    coreRepository.Credentials = System.Net.CredentialCache.DefaultNetworkCredentials;
                    coreRepository.IgnoreMissingProperties = true;
                    coreRepository.IgnoreResourceNotFoundException = true;

                    coreRepository.SendingRequest += coreRepository_SendingRequest;
                    //coreRepository.SendingRequest2 += coreRepository_SendingRequest2;
             }
                return coreRepository;
            }
        }
       private biz.dfch.CS.Appclusive.Api.Core.Core coreRepository;

        void coreRepository_SendingRequest(object sender, SendingRequestEventArgs e)
        {
            e.RequestHeaders["Accept"] = "application/json";
            e.RequestHeaders.Add("randNum", "test");
        }

But, adding a HEader works with changing it so far no luck
In this POST (2008!!) https://social.msdn.microsoft.com/Forums/en-US/cf849553-c4e4-4f3c-882b-216d7588108f/request-json-from-dataservicecontext?forum=adodotnetdataservices 
a person from Microsoft sais . "Since the client code is not written to handle json response, we don't allow Accept headers to be over-ridden. Your best bet would be to use HttpWebRequest directly and then handle the json response yourself."

**Comment by dfch** [comment]
use `biz.dfch.CS.Appclusive.Api.Core.Core.Format.UseJson()` to change the client to use `json`

**Comment by ChrEggenberger** [comment]
Yes, this works.

Bit it does not solve the problem with returning jobs id's
"The metadata URI 'http://172.19.115.33/Appclusive/api/Core/$metadata#Edm.String' is not valid for the expected payload kind 'Entry'."

It may work when the job is returned as an object (entitiy) ot just the id.
