### ISSUE TITLE
Same description for both VDI dropdown entries

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Appclusive.UI#45]
The entries should have the following names

* `Add personal VDI`
* `Add technical VDI`

![09 12](https://cloud.githubusercontent.com/assets/5937292/11696101/e85b685c-9eb2-11e5-81f6-07526b64a152.png)

**Comment by ChrEggenberger** [comment]
Already fixed with the latest commits

________________________________
Von: Rufer<mailto:notifications@github.com>
Gesendet: ‎09.‎12.‎2015 20:25
An: dfensgmbh/biz.dfch.CS.Appclusive.UI<mailto:biz.dfch.CS.Appclusive.UI@noreply.github.com>
Cc: Christian Eggenberger<mailto:eggenberger@afca.ch>
Betreff: Re: [biz.dfch.CS.Appclusive.UI] Same description for both VDI dropdown entries (#45)


Assigned #45<https://github.com/dfensgmbh/biz.dfch.CS.Appclusive.UI/issues/45> to @ChrEggenberger<https://github.com/ChrEggenberger>.

**Comment by ChrEggenberger** [comment]
labels changed
